# Site settings
name: Mohit Nihalani
title: Mohit Nihalani | Software Engineer
description: A polymathic software engineer
url: http://www.mohitnihalani.com/
baseurl: ""
email: mn2643@nyu.edu
cover: img/og.png
logo: img/emojis/technologist.png
social:
  - title: email
    url: mailto:mn2643@nyu.edu
  - title: github
    url: https://github.com/mohitnihalani
  - title: linkedin
    url: https://www.linkedin.com/in/mohit-nihalani/
  - title: medium
    url: https://medium.com/@nihalanim9
  - title: twitter
    url: https://twitter.com/MohitNihalani9

  
sass: 
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

# theme: jekyll-theme-minimal