# Site settings
name: Mohit Nihalani
title: Mohit Nihalani | Software Engineer
description: A polymathic software engineer
url: http://www.mohitnihalani.com/
baseurl: ""
email: mohitnihalani.in@gmail.com
cover: img/og.png
logo: img/emojis/technologist.png
resume: /pdfs/resume.pdf
social:
  - title: email
    url: mailto:mohitnihalani.in@gmail.com
  - title: github
    url: https://github.com/mohitnihalani
  - title: linkedin
    url: https://www.linkedin.com/in/mohit-nihalani/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
