# Site settings
name: Mohit Nihalani
title: Mohit Nihalani | Software Engineer | ML Engineer
description: Machine Learning and Distributed Systems enthusiast, who wants to make machine learning extensible and cheap.
url: http://www.mohitnihalani.com/
baseurl: ""
email: mohitnihalani.in@gmail.com
cover: img/og.png
logo: img/emojis/technologist.png
social:
  - title: email
    url: mailto:mohitnihalani.in@gmail.com
  - title: github
    url: https://github.com/mohitnihalani
  - title: linkedin
    url: https://www.linkedin.com/in/mohit-nihalani/
  - title: medium
    url: https://medium.com/@nihalanim9
  - title: twitter
    url: https://twitter.com/MohitNihalani9

  
sass: 
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

# theme: jekyll-theme-minimal